services:

  nginx:
    container_name: nginx
    image: nginx:latest
    network_mode: host
    restart: always
    volumes:
      - ${home_path}/config/nginx/conf/:/etc/nginx/conf.d/:ro
      - ${home_path}/config/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/dns-cloudflare:latest
    volumes:
      - ${home_path}/config/certbot/conf/:/etc/letsencrypt/:rw

  drawio:
    image: jgraph/drawio
    container_name: drawio
    ports:
      - "8016:8080"
      - "8017:8443"
    environment:
      TZ: Asia/Shanghai
      PUBLIC_DNS: lich.tech
      DRAWIO_BASE_URL: https://lich.tech:1443
      DRAWIO_VIEWER_URL: https://lich.tech:1443/js/viewer.min.js
      DRAWIO_LIGHTBOX_URL: https://lich.tech:1443
      DRAWIO_GITLAB_ID: "0e672d9bb4ea8c3952c645c5859ad39987c76c815cdd8ae55553f0191528bfda"
      DRAWIO_GITLAB_SECRET: "gloas-1d7e8dab2295039b66796543d1e5545ab6718d2b8ade80bc051d3610c42c50d6"
      DRAWIO_GITLAB_URL: "https://lich.tech:8018"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://192.168.2.20:8016 || exit 1"
        ]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'lich.tech'
    environment:
      TZ: Asia/Shanghai
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://lich.tech:8018'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        nginx['ssl_certificate'] = "/etc/letsencrypt/live/lich.tech/fullchain.pem"
        nginx['ssl_certificate_key'] = "/etc/letsencrypt/live/lich.tech/privkey.pem"
        nginx['redirect_http_to_https'] = true
    ports:
      - '8929:8929'
      - '8018:8018'
      - '2424:22'
    volumes:
      - ${home_path}/data/gitlab/config:/etc/gitlab
      - ${home_path}/data/gitlab/logs:/var/log/gitlab
      - ${home_path}/data/gitlab/data:/var/opt/gitlab
      - '${home_path}/config/certbot/conf:/etc/letsencrypt:ro'
    shm_size: '256m'
  #  jellyfin:
  #    image: linuxserver/jellyfin:latest
  #    network_mode: host
  #    container_name: jellyfin
  #    environment:
  #      - PUID=0
  #      - PGID=0
  #      - TZ=Asia/Shanghai
  #    volumes:
  #      - ${home_path}/config/jellyfin:/config
  #      - ${home_path}/data/Series:/data/tvshows
  #      - ${home_path}/data/Movies:/data/movies
  #      - /etc/letsencrypt/live/lich.tech/:/data/cert
  #      - /opt/vc/lib:/opt/vc/lib
  #    devices:
  #      - /dev/vcsm-cma:/dev/vcsm #optional
  #      - /dev/vchiq:/dev/vchiq #optional
  #      - /dev/video10:/dev/video10 #optional
  #      - /dev/video11:/dev/video11 #optional
  #      - /dev/video12:/dev/video12 #optional
  #    ports:
  #      - 8096:8096
  #      - 8920:8920 #optional
  #      - 7359:7359/udp #optional
  #      - 1900:1900/udp #optional
  #    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    #    mem_limit: 1024M
    #    cpus: 1
    restart: always
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000 # 注意替换
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080 # QB webui的端口，你可以换成其他端口
    volumes:
      - ${home_path}/config/qbittorrent:/config
      - ${home_path}/Downloads:/downloads # 替换成你自己的下载文件夹
      - ${home_path}/data/Anime:/downloads/Bangumi
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sS 'http://localhost:8080' || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 6

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000 # 注意替换
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - ${home_path}/config/jackett:/config
      - ${home_path}/Downloads:/downloads # 替换成你自己的下载文件夹
  #    ports:
  #      - 9117:9117

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000 # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/radarr:/config
      - ${home_path}:/volume0
      - ${home_path}/data:/volume1 # 注意这里不再是下载文件夹，需要是下载/电影/剧集文件夹的母文件夹
  #    ports:
  #      - 7878:7878

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000 # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/sonarr:/config
      - ${home_path}:/volume0
      - ${home_path}/data/:/volume1 # 注意这里不再是下载文件夹，需要是下载/电影/剧集文件夹的母文件夹
  #    ports:
  #      - 8989:8989
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000 # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/ombi:/config
  #    ports:
  #      - 3579:3579

  #  chinesesubfinder:
  #    image: allanpk716/chinesesubfinder:latest-lite
  #    volumes:
  #      -  ${home_path}/config/chinesesubfinder:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
  #      -  ${home_path}/data/Series:/Series    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
  #      -  ${home_path}/data/Movies:/Movies    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
  #    environment:
  #      - PUID=1000         # uid
  #      - PGID=1000          # gid
  #      - PERMS=true        # 是否重设/media权限
  #      - TZ=Asia/Shanghai  # 时区
  #      - UMASK=022         # 权限掩码
  #    restart: always
  #    network_mode: host
  #    hostname: chinesesubfinder
  #    container_name: chinesesubfinder
  #   ports:
  #     - 19035:19035  # 从0.20.0版本开始，通过webui来设置
  #     - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
  #   logging:
  #       driver: "json-file"
  #       options:
  #         max-size: "100m" # 限制docker控制台日志大小，可自行调整


  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000 # 注意替换
      - TYPECHO_DB_ADAPTER=SQLite # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/bazarr:/config
      - ${home_path}/data/Movies:/volume1/Data/Movies # 替换成你自己的电影文件夹
      - ${home_path}/data/Series:/volume1/Data/Series # 替换成你自己的剧集文件夹
      # - /volume1:/volume1 你也可以选择这种整个映射的形式
      # - /volume2:/volume2
      #    ports:
      #     - 6767:6767
  auto_bangumi:
    image: estrellaxd/auto_bangumi:latest
    container_name: auto_bangumi
    #    ports:
    #      - 7892:7892
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${home_path}/config/auto_bangumi/config:/app/config #不要动
      - ${home_path}/config/auto_bangumi/data:/app/data #不要动
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${home_path}/config/calibre:/config
      - ${home_path}/data/Books:/books
      - ${home_path}/config/calibre/metadata_provider/NewDouban.py:/app/calibre-web/cps/metadata_provider/NewDouban.py
    #    ports:
    #      - 8083:8083
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${home_path}/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${home_path}/config/nextcloud:/config
      - ${home_path}/data/Files:/data
    ports:
      - 8443:443
    restart: unless-stopped
