version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    network_mode: host
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/jellyfin:/config
      - ${home_path}/data/Series:/data/tvshows
      - ${home_path}/data/Movies:/data/movies
      - /etc/letsencrypt/live/lich.tech/:/data/cert
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vcsm-cma:/dev/vcsm #optional
      - /dev/vchiq:/dev/vchiq #optional
      - /dev/video10:/dev/video10 #optional
      - /dev/video11:/dev/video11 #optional
      - /dev/video12:/dev/video12 #optional
#    ports:
#      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    mem_limit: 1024M
#    cpus: 1
    restart: always
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000  # 注意替换
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080 # QB webui的端口，你可以换成其他端口
    volumes:
      - ${home_path}/config/qbittorrent:/config
      - ${home_path}/Downloads:/downloads   # 替换成你自己的下载文件夹
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6



  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000  # 注意替换
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - ${home_path}/config/jackett:/config
      - ${home_path}/Downloads:/downloads   # 替换成你自己的下载文件夹
#    ports:
#      - 9117:9117

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/radarr:/config
      - ${home_path}:/volume0
      - ${home_path}/data:/volume1 # 注意这里不再是下载文件夹，需要是下载/电影/剧集文件夹的母文件夹
#    ports:
#      - 7878:7878

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/sonarr:/config
      - ${home_path}:/volume0
      - ${home_path}/data/:/volume1 # 注意这里不再是下载文件夹，需要是下载/电影/剧集文件夹的母文件夹
#    ports:
#      - 8989:8989
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/ombi:/config
#    ports:
#      - 3579:3579

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest-lite
    volumes:
      -  ${home_path}/config/chinesesubfinder:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      -  ${home_path}/data/Series:/Series    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      -  ${home_path}/data/Movies:/Movies    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
    environment:
      - PUID=1000         # uid
      - PGID=1000          # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    restart: always
    network_mode: host
    hostname: chinesesubfinder
    container_name: chinesesubfinder
 #   ports:
 #     - 19035:19035  # 从0.20.0版本开始，通过webui来设置
 #     - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整


  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # 注意替换
      - PGID=1000  # 注意替换
      - TYPECHO_DB_ADAPTER=SQLite  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ${home_path}/config/bazarr:/config
      - ${home_path}/data/Movies:/volume1/Data/Movies     # 替换成你自己的电影文件夹
      - ${home_path}/data/Series:/volume1/Data/Series     # 替换成你自己的剧集文件夹
      # - /volume1:/volume1 你也可以选择这种整个映射的形式
      # - /volume2:/volume2
#    ports:
#     - 6767:6767
  auto_bangumi:
    image: estrellaxd/auto_bangumi:latest
    container_name: auto_bangumi
#    ports:
#      - 7892:7892
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${home_path}/config/auto_bangumi/config:/app/config #不要动
      - ${home_path}/config/auto_bangumi/data:/app/data #不要动
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${home_path}/config/calibre:/config
      - ${home_path}/data/Books:/books
      - ${home_path}/config/calibre/metadata_provider/NewDouban.py:/app/calibre-web/cps/metadata_provider/NewDouban.py
#    ports:
#      - 8083:8083
    restart: unless-stopped


  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${home_path}/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai